#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll='ls -laF --color=auto --group-directories-first' \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# Git
alias \
	g="git" \
	gp="git pull origin" \
	gf="git fetch origin" \
	gP="git push" \
	gPf="git push -f" \
	gc="git commit" \
	gr="git rebase main"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	d="sudo dnf" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

# Fav
alias \
	arch_info='inxi -Fxxxz' \
	virinit='eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"' \
	dst='sudo systemctl start docker' \
	dsp='sudo systemctl stop docker' \
	nuke='docker rm $(docker ps -a -q) && docker rmi $(docker images -q) --force' \
	sc='source ~/.config/zsh/.zshrc' \
	ipshow="ip addr show" \
	goto=". ~/.local/bin/goto.sh"
